### ISSUE TITLE
Feat req: start on feed

### ISSUE THREAD

**Issue by blinkelys** [Kei-K23/code-snip-share#3]
When signing in / registrering make it start on the feed page. It is hard as a first time user to find the feed btn.

**Comment by arkarmin-gg** [comment]
Hello @ARPCharlie, I fix that UI design for the user when they are not login or register, then it will show login and register button. If user is login, then it will show Get CodeSnipShare button and when click on button it will redirect to dashboard page

If user is logined

<img width="1417" alt="Screenshot 2024-08-04 at 20 58 45" src="https://github.com/user-attachments/assets/8e90d99c-1d79-4ecb-a608-3e0f7c727654">

If user is not login

<img width="1325" alt="Screenshot 2024-08-04 at 21 05 26" src="https://github.com/user-attachments/assets/6e916cfa-c2ed-4d7a-b2b9-311d6b664d73">
