### ISSUE TITLE
create a new snippet

### ISSUE THREAD

**Issue by issa-bourasse** [Kei-K23/code-snip-share#4]
i tryed to create a new code snippet it donsen't work it show "unable to create the snippet".

**Comment by arkarmin-gg** [comment]
Hello @issa-bourasse, I try and test create new snippet and it work. I will explain why your case is not work. I noticed that your email didn't contain user name like first name or last name and it cause the clerk webhook to create new user and cann't save in the database. I fixed that problem. Delete your user account and register again. Please let me know the issue still exist or not.
